language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy3
env:
  - PYTEST=5.0.1
  - PYTEST=5.1.3
  - PYTEST=5.2.4
  - PYTEST=5.3.5
  - PYTEST=5.4.1
  - PYTEST=6.0.2
  - PYTEST=6.1.0
install:
  - pip install -q pytest==$PYTEST
  - pip install -q -e .
  - pip install -q pre-commit
  - pre-commit install
script:
  - if [[ "$TRAVIS_PYTHON_VERSION" > "3.5" ]] && [[ "$TRAVIS_PYTHON_VERSION" != pypy* ]]; then pre-commit run --all-files --show-diff-on-failure; fi
  - py.test
